# Change the default prompt format
format = """\
[â•­â•´](238)\
$env_var\
[î‚¶](fg:#1d2230)\
$username\
[î‚°](bg:#3B76F0 fg:#1d2230)\
$directory\
[î‚°](fg:#3B76F0 bg:#86BBD8)\
[î‚°](bg:#06969A fg:#86BBD8)\
$git_branch\
$git_status\
[î‚°](fg:#06969A bg:#86BBD8)\
[î‚°](fg:#86BBD8 bg:#3B76F0)\
$docker_context\
[î‚°](fg:#3B76F0)
$fill\
$package\
$php\
$python\
$nodejs\
[î‚²](fg:#86BBD8)\ 
$status\
[î‚²](bg:#86BBD8 fg:blue)\ 
$cmd_duration\
[î‚²](fg:#1d2230 bg:blue)\ 
$time\
[î‚´](fg:#1d2230)\
\n[â•°â”€](238)$character"""

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white)'  # removed space between distro and rest for pwsh
variable = "STARSHIP_DISTRO"
disabled = false

# Change the default prompt characters
[character]
success_symbol = '[âœ](bold green) '
error_symbol = '[âœ—](bold red) '

[cmd_duration]
format = "[ ï™ $duration ]($style)"
style = "fg:bright-white bg:blue"

[directory]
style = "fg:#E4E4E4 bg:#3B76F0"
format = "[$path]($style)[$read_only]($read_only_style)"
read_only_style = "197"
read_only = " ğŸ”’ "
truncation_length = 8
truncation_symbol = 'â€¦/'

[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï€™"
"Music" = "ï€"
"Pictures" = "ï€¾"
"Desktop" = "ï„ˆ"
"Projects" = "î™¥"

[docker_context]
format = "via [ğŸ³ $context](bold blue) "

[fill]
symbol = ' '

[git_branch]
symbol = "ğŸŒ±"
truncation_length = 4
truncation_symbol = ""
style = "bg:#FCA17D"
format = 'on [[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bg:#FCA17D"    
conflicted = "ğŸ³"
up_to_date = "ï† "
untracked = "ğŸ¤·"
ahead = "ğŸï¸ğŸ’¨â‡¡${count}"
diverged = "ğŸï¸ğŸ’¨â‡•â‡¡${ahead_count} ğŸ¢â‡£${behind_count}"
behind = "ğŸ¢â‡£${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“"
staged = '[ğŸ—ƒï¸+\($count\)](green)'
renamed = "ğŸ“›"
deleted = "ğŸ—‘ï¸"

#[kubernetes]
#format = 'on [ïˆš$context\($namespace\)](bold purple) '
#disabled = false
#[kubernetes.context_aliases]
#"clcreative-k8s-staging" = "cl-k8s-staging"
#"clcreative-k8s-production" = "cl-k8s-prod"

[nodejs]
symbol = "ğŸ¤–"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
#format = 'via [ğŸ¤– $version](bold green) '

[package]
format = 'via [ğŸ $version](208 bold) '

[php]
symbol = "ğŸ˜"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'
#format = 'via [ğŸ”¹ $version](147 bold) '

[python]
symbol = "ğŸ "
python_binary = "python3"

[status]
style = 'bg:#86BBD8'
symbol = 'âŒ '
success_symbol = 'âœ“ '
not_found_symbol = 'ğŸ” '
sigint_symbol = 'ğŸ§± '
format = '[ \[$symbol$common_meaning$signal_name$maybe_int\]]($style)'
map_symbol = true
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#3B76F0 bg:#1d2230"
format = '[ ğŸ•™ $time ]($style)'

[username]
style_user = "fg:#3B76F0 bg:#1d2230"
style_root = 'black bold'
format = '[ï€‘ $user]($style) '
disabled = false
show_always = true
